package chitchat.model.enumeration;

public enum NotificationType {
    FRIEND_REQUEST_RECEIVED,
    FRIEND_REQUEST_ACCEPTED,
    FRIEND_REQUEST_REJECTED,
    FRIEND_REQUEST_CANCELLED,
    FRIEND_REQUEST_REMOVED,
    USER_TYPING_START,
    USER_TYPING_STOP,
    GROUP_MESSAGE_RECEIVED,
    GROUP_MEMBER_JOINED,
    GROUP_MEMBER_LEFT,
    GROUP_MEMBER_REMOVED
}
